language: r
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - libsodium-dev
cache:
  apt: true
  packages: true
after_success:
  - Rscript -e 'covr::codecov()'
jobs:
  include:
    - os: linux
    - os: osx
  allow_failures:
    - os: osx
